Auth Customization Options
azalea-rs/azalea pull request #159
Opened 2024-06-19 10:13 UTC by AS1100K

## What this PR adds?
This PR addresses and closes the issue #150. It introduces two new functions in `azalea_client::Account`:
* `microsoft_with_custom_client_id` 
* `with_microsoft_access_token_and_custom_client_id`.

This PR will allow the developer, to customize the `client_id`, or use the nintendo switch one.

## Backwards Compatibility?
The existing functions `microsoft` and `with_microsoft_access_token` will maintain their current functionality. However, their implementations have been refactored to depend on the new functions `microsoft_with_custom_client_id` and `with_microsoft_access_token_and_custom_client_id` to avoid code duplication and facilitate easier maintenance.

2024-06-27 04:24 UTC, 1zun4 commented
This is great, but you are missing two important flags:
- RpsTicket format (see https://github.com/CCBlueX/azalea/commit/ca3e419904fd37b6f379c78242ca1e2b0139d9b5)
- Scope (see https://github.com/CCBlueX/azalea/commit/2b7484af0dd7bde6d68a7395f59d41e98ba7f2dc)

If you are using your own ClientID, these changes are also mandatory. Otherwise this option is useless.

2024-06-27 11:11 UTC, AS1100K commented
> I saw that you added a custom scope, but then removed it as it was apparently not needed? What is the reason for this? - [d2bb6f4](https://github.com/azalea-rs/azalea/commit/d2bb6f4b6d1350b5973cde7c0eeed2570c0dfe7f)

I removed the custom scope because that time i thought, that you will not require additional permissions but looking it again, i realize that having custom scope would allow to do more stuff, maybe send a email, etc.

I will commit add this back also RpsTicket format and commit the changes

2024-07-07 10:51 UTC, veronoicc commented
I just looked trough it an saw a lot of parameters with &'static str, and to my knowledge getting somethink as an &'static is not really possible (unless with a hardcoded str in this case) without leasing memory. Maybe using a non 'static str here is better?

2024-07-07 10:52 UTC, veronoicc commented
Meant fields in the AuthOps struct mb

2024-08-11 11:25 UTC, mat-1 requested changes
Thank you for making this, I'm sorry for taking so long to get to it. This looks good, the main thing I think should be changed is using `Option<&str>`  instead of `&str` for all the public functions that take a client_id and scope. I can resolve everything here tomorrow (I'm going to sleep after writing this) unless you want to.

By the way, I recommend you also run `cargo fmt` to standardize the formatting on some of the code.

2024-08-11 11:25 UTC, mat-1 commented on azalea-client/src/account.rs
> +    /// // Or, `azalea_auth::get_ms_link_code(&client, Some(client_id)).await?`
The second line here should be taking two arguments.
```suggestion
    /// let res = azalea_auth::get_ms_link_code(&client, None, None).await?;
    /// // Or, `azalea_auth::get_ms_link_code(&client, Some(client_id), None).await?`
```

2024-08-11 11:25 UTC, mat-1 commented on azalea-auth/src/auth.rs
> +    scope: &str
I think this should take `Option<&str>`s to make it like some of the other functions and so the user isn't required to pass a client id and scope.
```suggestion
    client_id: Option<&str>,
    scope: Option<&str>
```

2024-08-11 11:25 UTC, mat-1 commented on azalea-auth/src/auth.rs
> +    client_id: &str
```suggestion
    client_id: Option<&str>
```

2024-08-11 11:25 UTC, mat-1 commented on azalea-auth/src/auth.rs
> +    scope: &str
```suggestion
    client_id: Option<&str>,
    scope: Option<&str>
```

2024-08-11 11:25 UTC, mat-1 commented on azalea-auth/src/auth.rs
> +/// let msa = azalea_auth::get_ms_auth_token(client, res, "client_id").await?;
These "client_id" and "scope" should just be `None` so the example works by default.

2024-08-11 11:25 UTC, mat-1 commented on azalea-auth/src/auth.rs
> +
There's other client ids where `d=` shouldn't be added, I think the user should be responsible for adding it themselves (get_minecraft_token already documents it).
```suggestion
```

2024-08-11 11:25 UTC, mat-1 commented on azalea-auth/src/auth.rs
> +    /// If you choose to use your own microsoft authentication instead of using nintendo switch, just put your client_id here
Tiny nitpick here but I've been trying to keep the grammar in the docs consistent, mainly just capitalizing proper nouns (so Microsoft and Nintendo Switch should be capitalized here) and adding periods at the end of sentences.

2024-08-11 11:25 UTC, mat-1 commented on azalea-client/src/account.rs
> +    /// let msa = azalea_auth::get_ms_auth_token(&client, res, "client_id").await?;
```suggestion
    /// let msa = azalea_auth::get_ms_auth_token(&client, res, None).await?;
```

2024-08-11 21:54 UTC, mat-1 approved these changes

2024-08-11 21:54 UTC, merged